name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Cache modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Download modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Run tests
      run: go test ./...
